import { RemotePlaybackGuard } from "../services/RemotePlaybackGuard";
import { SyncEngine } from "../services/SyncEngine";
import { WatchPartyGatewayEngine } from "../services/WatchPartyGatewayEngine";
import { ISyncAdapter, QualityLevel } from "./ISyncAdapter";
import { PlaybackCoordinator } from "./PlaybackCoordinator";

export class PartySyncAdapter implements ISyncAdapter {
    private coordinator: PlaybackCoordinator | null = null;
    
    constructor(
        private readonly localEngine: SyncEngine,
        private readonly gateway: WatchPartyGatewayEngine,
        private readonly streamUrl: string,
        private readonly roomId: string,
        private readonly roomCode: string,
        private readonly userId: string,
        private readonly ownerId: string,
        private readonly remotePlaybackGuard: RemotePlaybackGuard,
    ) {
        console.log("[PartySyncAdapter] Created", {
            userId: this.userId,
            ownerId: this.ownerId,
            isOwner: this.isOwner,
        });
    }

    private createCoordinator(): PlaybackCoordinator {
        return new PlaybackCoordinator(
            this.localEngine,
            this.gateway,
            this.userId,
            this.remotePlaybackGuard,
        );
    }

    attachVideo(video: HTMLVideoElement): void {
        this.localEngine.attachElement({
            element: video,
            streamUrl: this.streamUrl,
        });

        if (this.coordinator) {
            this.coordinator.dispose();
        }

        this.coordinator = this.createCoordinator();
        this.coordinator.start();
    }
    
    detachVideo(): void {
        if (this.coordinator) {
            this.coordinator.stop();
        }

        this.localEngine.detachElement();
    }

    async play(): Promise<void> {
        if (this.remotePlaybackGuard.isActive) {
            console.log("[PartySyncAdapter] Ignoring PLAY generated by remote playback");

            return;
        }

        if (!this.isOwner) {
            console.log(
                "[PartySyncAdapter] Ignoring PLAY from non-owner",
                {
                    userId: this.userId,
                    ownerId: this.ownerId,
                }
            );

            return;
        }

        const playhead = this.localEngine.getCurrentTime();

        console.log("[PartySyncAdapter] PLAY requested", {
            roomId: this.roomId,
            roomCode: this.roomCode,
            userId: this.userId,
            playhead,
        });

        await this.localEngine.play();

        this.gateway.emitPlaybackPulse({
            roomId: this.roomId,
            roomCode: this.roomCode,
            action: "PLAY",
            playhead: this.localEngine.getCurrentTime()
        });
    }

    async pause(): Promise<void> {
        if (this.remotePlaybackGuard.isActive) {
            console.log(
                "[PartySyncAdapter] Ignoring PAUSE generated by remote playback"
            );

            return;
        }

        if (!this.isOwner) {
            console.log(
                "[PartySyncAdapter] Ignoring PAUSE from non-owner",
                {
                    userId: this.userId,
                    ownerId: this.ownerId,
                }
            );

            return;
        }

        const playhead = this.localEngine.getCurrentTime();

        console.log("[PartySyncAdapter] PAUSE requested", {
            roomId: this.roomId,
            roomCode: this.roomCode,
            userId: this.userId,
            playhead,
        });

        await this.localEngine.pause();

        this.gateway.emitPlaybackPulse({
            roomId: this.roomId,
            roomCode: this.roomCode,
            action: "PAUSE",
            playhead:  this.localEngine.getCurrentTime()
        });
    }

    seek(seconds: number): void {
        if (this.remotePlaybackGuard.isActive) {
            console.log(
                "[PartySyncAdapter] Ignoring SEEK generated by remote playback"
            );

            return;
        }

        if (!this.isOwner) {
            console.log(
                "[PartySyncAdapter] Ignoring SEEK from non-owner",
                {
                    userId: this.userId,
                    ownerId: this.ownerId,
                    playhead: seconds,
                }
            );

            return;
        }

        console.log("[PartySyncAdapter] SEEK requested", {
            roomId: this.roomId,
            roomCode: this.roomCode,
            userId: this.userId,
            playhead: seconds,
        });

        this.localEngine.seek(seconds);

        this.gateway.emitPlaybackPulse({
            roomId: this.roomId,
            roomCode: this.roomCode,
            action: "SEEK",
            playhead: seconds
        });
    }

    dispose(): void {
        if (this.coordinator) {
            this.coordinator.dispose();
            this.coordinator = null;
        }

        this.localEngine.dispose();
    }

    getQualityLevels(): QualityLevel[] {
        return this.localEngine.getQualityLevels();
    }

    getCurrentQualityIndex(): number {
        return this.localEngine.getCurrentQualityIndex();
    }

    setQualityLevel(level: number): void {
        this.localEngine.setQualityLevel(level);
    }

    getCurrentTime(): number {
        return this.localEngine.getCurrentTime();
    }

    private get isOwner(): boolean {
        return this.userId === this.ownerId;
    }
}